# -*- coding: utf-8 -*-
"""M2 Ch Merge , Join, Concat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zNZcFIrslHU4hyPBk4yzgYyGun6B777-

# Merge
"""

import pandas as pd

df1= pd.DataFrame({'A':[2,3,4,5],'B':['A','B','C','D']})
df2= pd.DataFrame({'A':[2,4,6,8],'B':['A','C','E','F']})

pd.merge(df1,df2)

df3=pd.merge(df1,df2)
print(df3)

'''df1= pd.DataFrame({'A':[2,3,4,5],'B':['A','B','C','D']})
df2= pd.DataFrame({'A':[2,6,8],'B':['A','C','E','F']})'''

#ValueError: All arrays must be of the same length

df1= pd.DataFrame({'A':[2,3,4,5],'B':['A','B','C','D']})
df2= pd.DataFrame({'A':[2,4,6,8],'C':['A','C','E','F']})

df3=pd.merge(df1,df2)
print(df3)

pd.merge(df1,df2,on='A',how='inner')

pd.merge(df1,df2,on='A',how='outer')

pd.merge(df1,df2,on='A',how='left')

pd.merge(df1,df2,on='A',how='right')

# SAME COLUMN VALUE
df1= pd.DataFrame({'A':[2,3,4,5],'B':['A','B','C','D']})
df2= pd.DataFrame({'A':[2,3,4,5],'B':['Z','X','E','F']})
pd.merge(df1,df2)

'''import pandas as pd
df1= pd.DataFrame({'A':[2,3,4,5],'B':['A','B','C','D']})
df2= pd.DataFrame({'C':[2,4,6,8],'D':['A','C','E','F']})
df3=pd.merge(df1,df2)
print(df3)
'''
"""  "No common columns to perform merge on. "
   1574                         f"Merge options: left_on={left_on}, "

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False"""



"""## CONCAT"""

import pandas as pd

roll_no1 =pd.Series([1,2,3,4])
roll_no2= pd.Series([10,20,30,40])
pd.concat([roll_no1,roll_no2])

# to avoid indexing again  like in above output  ,,so axis used to avoid that (axis =1 used to make another column)

roll_no1 =pd.Series([1,2,3,4])
roll_no2= pd.Series([10,20,30,40])
pd.concat([roll_no1,roll_no2],axis=0,ignore_index=True)

df1=pd.DataFrame({'A':[2,3,4],'B':['A','B','C']})
df2=pd.DataFrame({'A':[2,4,6],'B':['A','C','E']})
pd.concat([df1,df2],axis=1)

df1=pd.DataFrame({'A':[2,3,4],'B':['A','B','C']})
df2=pd.DataFrame({'A':[2,4,6],'B':['A','C','E']})
pd.concat([df1,df2],join='inner')
#

#ValueError: Only can inner (intersect) or outer (union) join the other axis
'''df1=pd.DataFrame({'A':[2,3,4],'B':['A','B','C']})
df2=pd.DataFrame({'A':[2,4,6],'B':['A','C','E']})
pd.concat([df1,df2],join='left')'''

df1=pd.DataFrame({'A':[2,3,4],'B':['A','B','C']})
df2=pd.DataFrame({'A':[2,4,6],'B':['A','C','E']})
pd.concat([df1,df2],axis=0,keys=(['Pragya',"Payal"]))

df1=pd.DataFrame({'A':[2,3,4]})#'B':['A','B','C']})
df2=pd.DataFrame({'A':[2,4,6],'B':['A','C','E']})
pd.concat([df1,df2],axis=0)

'''df1=pd.DataFrame({'A':[2,3],'B':['A','B','C']})
df2=pd.DataFrame({'C':[2,4,6],'D':['A','E','F']})
pd.concat([df1,df2],axis=0)

ValueError: All arrays must be of the same length'''

df1=pd.DataFrame([2,3,4])#,'B':['A','B','C']})
df2=pd.DataFrame([2,4])#,'B':['A','C','E']})
pd.concat([df1,df2],axis=1)

