# -*- coding: utf-8 -*-
"""Module 2(Series and DataFrame) .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tvY3yVcPScRNdFQzIKskLWrxv1hniJBh

##  Chapter 1

## Data Manipulation with Pandas

# 1. Series
"""

import pandas as pd    # alies  (as)

Marks=[90,91,92,93,94,94]
ds=pd.Series(Marks)
print(ds)
print(type(ds))

#customized index
Marks=[90,91,92,93,94,94]
ds=pd.Series(Marks,index=['a','b','c','d','e','f'])


print(ds)

'''Marks=[90,91,92,93,94,94]
ds=pd.Series(Marks,index=['a','b','c','d','e'])  #  Length of values (6) does not match length of index (5)


print(ds)
'''

'''Marks=[90,91,92,93,94,94]
ds=pd.Series(Marks,index=['a','b','c','d','e','f','g'])#ValueError: Length of values (6) does not match length of index (7)


print(ds)'''

Marks=[90,91,92,93,94,94]
ds=pd.Series(Marks,index=['a','b','c','d','e','f'],dtype=float)


print(ds)

# add file name
Marks=[90,91,92,93,94,94]
ds=pd.Series(Marks,index=['a','b','c','d','e','f'],dtype=float,name="marksheet")


print(ds)

"""## 1.1 Common Operation"""

#sum
print(ds.sum())

#min
print("min no in series: ",ds.min())

#max
print("max no in series: ",ds.max())

#mean
print("mean of series: ", ds.mean())

"""## 1.2 Indexing and Slicing"""

print("access elemnet by int",ds["a"])

print("access elemnet by variable",ds[2])

print("Slicing in Series",ds[0:3])

print("Slicing in Series",ds['a':'d'])

"""## 1.3 Vectorized Operations"""

print(ds+5)

print(ds*1)

print(ds/1)

print(ds%1)

print(ds**1)

"""dictionary can be a series"""

info={
    "name" : "Pragya",
    "age":21
}
ds1=pd.Series(info)
print(ds1)

ds1['name']

ds1.index

"""# Create a series with single digit"""

num=pd.Series(5)
print(num)

num=pd.Series(5,index=[1,2,3,4,5])
print(num)

#'we can  create multiple index with single value'

num=pd.Series(5,index=[1,2,3,4,5])
num1=pd.Series(10,index=[1,2,3,4,5])
print(num+num1)

# addition on basis of index
num=pd.Series(5,index=[1,2,3,4,5])
num1=pd.Series(10,index=[0,6,3,4,5])
print(num+num1)

#nan = not a number
'''same index  additon will perform
but in case differnet index it will show NaN
'''

'''# different index it will show NaN
#indexing should be same'''
num=pd.Series(5,index=[1,2,3,4,5])
num1=pd.Series(10,index=['a','b','c','d','e'])
print(num+num1)

"""## 2. main data structure

## Pandas DataFrame
"""

import pandas as pd

student={
    'Name':['Pragya','Payal','Niharika'],
    'Roll no.':[70,67,62],
    'Marks':[92,93,95]
}

df=pd.DataFrame(student)
print(df)

# All arrays must be of the same length
'''student={
    'Name':['Pragya','Payal','Niharika'],
    'Roll no.':[70,67,62],
    'Marks':[93,95]    #ValueError: All arrays must be of the same length
}

df=pd.DataFrame(student)
print(df)'''

student={
    'Name':['Pragya','Payal','Niharika'],
    'Roll no.':[70,67,62],
    'Marks':[92,93,95]
}

df=pd.DataFrame(student)
print(df)

# Creating a dataframe with list

student_info=[['a','b','c'],[20,30,40]]
df=pd.DataFrame(student_info)
df
#print(df)

#Creating dataframe with multiple series
import pandas as pd
SR={
     'Name':pd.Series(['Pragya','Niharika','Payal']),
     'Roll no':pd.Series([70,67,62])
 }
df=pd.DataFrame(SR)
df

"""## 2.1 Arithmetic Opeartions"""

var=pd.DataFrame({'A':[1,2,3],'B':[3,5,6]})
var

var["C"]=var['A']+var['B']
var

"""## 2.3 SORTING"""

#filter
var['Python']=var["C"]>10
var

"""# Handling missing values"""

# create a dict. using np.NaN
#
import numpy as np
student={
    'Name':['Pragya','Payal','Niharika','Chhavi','Sarthak'],
    'Roll no.':[70,67,62,34,np.nan],
    'Marks':[92,93,np.nan,98,99],
    'Subject':['Chem',np.nan,'BIO',np.nan,'physics'],
    'City':['noida','noida','siwan',np.nan,np.nan]
}

df=pd.DataFrame(student)
df

df.info()

df.isnull()
#non null=false and null=true

df.isnull().sum()

print(df.isnull().sum().sum())

df.dropna()

df['Marks']=df['Marks'].fillna(0)

df.dropna(subset=['Roll no.'])

df['Marks']=df['Marks'].fillna(df['Marks'].mean())
print(df['Marks'])

df['Name'].fillna("unknown")

